#ifndef _JSON_VERSION_H_INCLUDED_
#define _JSON_VERSION_H_INCLUDED_

# define JSONCPP_VERSION_STRING      "0.6.0-dev"
# define JSONCPP_VERSION_MAJOR       0
# define JSONCPP_VERSION_MINOR       6
# define JSONCPP_VERSION_PATCH       0
# define JSONCPP_VERSION_QUALIFIER   -dev
# define JSONCPP_VERSION_HEXA       ((JSONCPP_VERSION_MAJOR << 24) | (JSONCPP_VERSION_MINOR << 16) | (JSONCPP_VERSION_PATCH << 8))

#endif // _JSON_VERSION_H_INCLUDED_
